//! Tauri-independent contracts for media inspection and encoding jobs.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct ToolInfo {
    pub id: String,
    pub name: String,
    pub available: bool,
    pub path: Option<String>,
    pub version: Option<String>,
    pub detail: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct MediaFile {
    /// Stable for the same canonical input path; this is not a content hash.
    pub id: String,
    pub path: String,
    pub name: String,
    /// Decimal text preserves byte counts beyond JavaScript's safe integer range.
    pub size_bytes: String,
    pub duration_seconds: Option<f64>,
    pub format: Option<String>,
    pub streams: Vec<MediaStream>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct MediaStream {
    /// Original source stream index, independent of presentation order.
    pub index: u32,
    pub kind: String,
    pub codec: Option<String>,
    pub width: Option<u32>,
    pub height: Option<u32>,
    /// Original rational frame rate, for example `24000/1001`.
    pub frame_rate: Option<String>,
    pub sample_rate: Option<u32>,
    pub channels: Option<u32>,
    pub language: Option<String>,
    pub title: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, thiserror::Error)]
#[serde(rename_all = "camelCase")]
#[error("{message}")]
pub struct AppError {
    pub code: String,
    pub message: String,
    pub path: Option<String>,
}

impl AppError {
    pub fn new(code: impl Into<String>, message: impl Into<String>, path: Option<String>) -> Self {
        Self {
            code: code.into(),
            message: message.into(),
            path,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EncodeRequest {
    pub input_path: String,
    pub output_path: String,
    pub crf: u8,
    pub preset: u8,
    pub audio_bitrate_kbps: u16,
    /// None preserves each audio track's channel count.
    pub audio_channels: Option<u8>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub enum JobStatus {
    Preparing,
    Encoding,
    Muxing,
    Validating,
    Publishing,
    Completed,
    Cancelled,
    Failed,
    Interrupted,
}

impl JobStatus {
    pub fn is_active(self) -> bool {
        matches!(
            self,
            Self::Preparing | Self::Encoding | Self::Muxing | Self::Validating | Self::Publishing
        )
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub struct EncodeJob {
    pub id: String,
    pub request: EncodeRequest,
    pub status: JobStatus,
    pub progress: Option<f64>,
    pub message: String,
    /// Decimal Unix epoch milliseconds, independent of the desktop's timezone.
    pub created_at_ms: String,
    pub updated_at_ms: String,
}

/// Single-file contract output keeps imports deterministic and drift checks simple.
pub fn typescript_contracts() -> String {
    let config = ts_rs::Config::default();
    let declarations = [
        ToolInfo::decl(&config),
        MediaStream::decl(&config),
        MediaFile::decl(&config),
        AppError::decl(&config),
        EncodeRequest::decl(&config),
        JobStatus::decl(&config),
        EncodeJob::decl(&config),
    ];
    let mut output =
        String::from("// Generated by media-core. Run pnpm contracts; do not edit.\n\n");
    for declaration in declarations {
        output.push_str("export ");
        output.push_str(&declaration);
        output.push_str("\n\n");
    }
    let normalized = output
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    format!("{}\n", normalized.trim_end())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ipc_preserves_large_byte_counts_and_explicit_missing_metadata() {
        let value = serde_json::to_value(MediaFile {
            id: "media-1".into(),
            path: "example.mkv".into(),
            name: "example.mkv".into(),
            size_bytes: "9007199254740993".into(),
            duration_seconds: None,
            format: None,
            streams: vec![],
        })
        .unwrap();
        assert_eq!(value["sizeBytes"], "9007199254740993");
        assert!(value["durationSeconds"].is_null());
        assert!(value.get("size_bytes").is_none());
        assert!(typescript_contracts().contains("sizeBytes: string"));
        assert!(typescript_contracts().contains("durationSeconds: number | null"));
    }
}
