use super::{Spec, ValueKind};

fn spec(
    name: &'static str,
    label: &'static str,
    bounds: (i32, i32),
    kind: ValueKind,
    choices: &'static [&'static str],
    group: &'static str,
    help: (&'static str, &'static str),
) -> Spec {
    Spec {
        name,
        label,
        flag: name,
        min: bounds.0,
        max: bounds.1,
        kind,
        choices,
        group,
        description: help.0,
        example: help.1,
    }
}

fn native(mut value: Spec) -> Spec {
    // Catalog identifiers are fixed literals. The prefix never comes from user input.
    value.flag = match value.name {
        "tune" => "--tune",
        "profile" => "--profile",
        "level" => "--level",
        "deblock" => "--deblock",
        "cqm" => "--cqm",
        "bframes" => "--bframes",
        "b-adapt" => "--b-adapt",
        "ref" => "--ref",
        "weightp" => "--weightp",
        "rc-lookahead" => "--rc-lookahead",
        "me" => "--me",
        "subme" => "--subme",
        "merange" => "--merange",
        "direct" => "--direct",
        "partitions" => "--partitions",
        "b-pyramid" => "--b-pyramid",
        "aq-mode" => "--aq-mode",
        "aq-strength" => "--aq-strength",
        "psy-rd" => "--psy-rd",
        "trellis" => "--trellis",
        "qcomp" => "--qcomp",
        "chroma-qp-offset" => "--chroma-qp-offset",
        "nr" => "--nr",
        "vbv-maxrate" => "--vbv-maxrate",
        "vbv-bufsize" => "--vbv-bufsize",
        "qpmin" => "--qpmin",
        "qpmax" => "--qpmax",
        "qpstep" => "--qpstep",
        "ipratio" => "--ipratio",
        "pbratio" => "--pbratio",
        "crf-max" => "--crf-max",
        "ac-bias" => "--ac-bias",
        "tx-bias" => "--tx-bias",
        "sharpness" => "--sharpness",
        "sharp-tx" => "--sharp-tx",
        "max-tx-size" => "--max-tx-size",
        "alt-ssim-tuning" => "--alt-ssim-tuning",
        "variance-boost-strength" => "--variance-boost-strength",
        "variance-octile" => "--variance-octile",
        "variance-boost-curve" => "--variance-boost-curve",
        "qp-scale-compress-strength" => "--qp-scale-compress-strength",
        "luminance-qp-bias" => "--luminance-qp-bias",
        "chroma-qm-min" => "--chroma-qm-min",
        "chroma-qm-max" => "--chroma-qm-max",
        "hbd-mds" => "--hbd-mds",
        "enable-qm" => "--enable-qm",
        "qm-min" => "--qm-min",
        "qm-max" => "--qm-max",
        "min-qp" => "--min-qp",
        "max-qp" => "--max-qp",
        "startup-qp-offset" => "--startup-qp-offset",
        "enable-dlf" => "--enable-dlf",
        "enable-tf" => "--enable-tf",
        "tf-strength" => "--tf-strength",
        "kf-tf-strength" => "--kf-tf-strength",
        "noise-adaptive-filtering" => "--noise-adaptive-filtering",
        "cdef-scaling" => "--cdef-scaling",
        "enable-cdef" => "--enable-cdef",
        "enable-restoration" => "--enable-restoration",
        "noise" => "--noise",
        "noise-chroma" => "--noise-chroma",
        "noise-chroma-from-luma" => "--noise-chroma-from-luma",
        "noise-size" => "--noise-size",
        "noise-norm-strength" => "--noise-norm-strength",
        "adaptive-film-grain" => "--adaptive-film-grain",
        "scm" => "--scm",
        "fast-decode" => "--fast-decode",
        "enable-overlays" => "--enable-overlays",
        "lookahead" => "--lookahead",
        "complex-hvs" => "--complex-hvs",
        "enable-variance-boost" => "--enable-variance-boost",
        "hierarchical-levels" => "--hierarchical-levels",
        _ => unreachable!("fixed catalog literal"),
    };
    value
}

fn number(
    name: &'static str,
    label: &'static str,
    min: i32,
    max: i32,
    group: &'static str,
    description: &'static str,
    example: &'static str,
) -> Spec {
    native(spec(
        name,
        label,
        (min, max),
        ValueKind::Whole,
        &[],
        group,
        (description, example),
    ))
}
fn decimal(
    name: &'static str,
    label: &'static str,
    min: i32,
    max: i32,
    group: &'static str,
    description: &'static str,
    example: &'static str,
) -> Spec {
    native(spec(
        name,
        label,
        (min, max),
        ValueKind::Decimal,
        &[],
        group,
        (description, example),
    ))
}
fn choice(
    name: &'static str,
    label: &'static str,
    choices: &'static [&'static str],
    group: &'static str,
    description: &'static str,
    example: &'static str,
) -> Spec {
    native(spec(
        name,
        label,
        (0, 0),
        ValueKind::Choice,
        choices,
        group,
        (description, example),
    ))
}
fn choice_list(
    name: &'static str,
    label: &'static str,
    choices: &'static [&'static str],
    group: &'static str,
    description: &'static str,
    example: &'static str,
) -> Spec {
    native(spec(
        name,
        label,
        (0, 0),
        ValueKind::ChoiceList,
        choices,
        group,
        (description, example),
    ))
}

pub(super) fn x264() -> Vec<Spec> {
    let tuning = "Tuning and profile";
    let motion = "Frames and motion";
    let quant = "Quantization and texture";
    let rate = "Rate control";
    vec![
        choice_list(
            "tune",
            "Tune",
            &[
                "film",
                "animation",
                "grain",
                "stillimage",
                "psnr",
                "ssim",
                "fastdecode",
                "zerolatency",
            ],
            tuning,
            "Combine source and playback tunes with commas.",
            "film,fastdecode",
        ),
        choice(
            "profile",
            "H.264 profile",
            &["baseline", "main", "high", "high10", "high422", "high444"],
            tuning,
            "Limit coding tools for a target decoder.",
            "high",
        ),
        choice(
            "level",
            "H.264 level",
            &[
                "1", "1b", "1.1", "1.2", "1.3", "2", "2.1", "2.2", "3", "3.1", "3.2", "4", "4.1",
                "4.2", "5", "5.1", "5.2", "6", "6.1", "6.2",
            ],
            tuning,
            "Declare decoder limits; x264 may warn if other settings exceed them.",
            "4.1",
        ),
        native(spec(
            "deblock",
            "Deblocking offsets",
            (-6, 6),
            ValueKind::PairWhole,
            &[],
            tuning,
            (
                "Alpha and beta offsets; negative values retain more texture.",
                "-1:-1",
            ),
        )),
        choice(
            "cqm",
            "Quantization matrix",
            &["flat", "jvt"],
            tuning,
            "Choose a flat or frequency-weighted matrix.",
            "flat",
        ),
        number(
            "bframes",
            "B-frame limit",
            0,
            16,
            motion,
            "Maximum consecutive B-frames.",
            "4",
        ),
        number(
            "b-adapt",
            "B-frame adaptation",
            0,
            2,
            motion,
            "How thoroughly B-frame placement is searched.",
            "2",
        ),
        number(
            "ref",
            "Reference frames",
            1,
            16,
            motion,
            "Maximum reference frames for motion search.",
            "4",
        ),
        number(
            "weightp",
            "Weighted P prediction",
            0,
            2,
            motion,
            "Weighted prediction can improve fades.",
            "2",
        ),
        number(
            "rc-lookahead",
            "Rate-control lookahead",
            0,
            250,
            motion,
            "Frames examined before rate and frame-type decisions.",
            "40",
        ),
        choice(
            "me",
            "Motion search",
            &["dia", "hex", "umh", "esa", "tesa"],
            motion,
            "Integer-pixel motion search method.",
            "umh",
        ),
        number(
            "subme",
            "Subpixel search",
            0,
            11,
            motion,
            "Subpixel motion and mode decision quality.",
            "8",
        ),
        number(
            "merange",
            "Motion search range",
            4,
            1024,
            motion,
            "Maximum motion-vector search distance.",
            "24",
        ),
        choice(
            "direct",
            "Direct B prediction",
            &["spatial", "temporal", "auto", "none"],
            motion,
            "Derive motion for direct B blocks.",
            "auto",
        ),
        choice_list(
            "partitions",
            "Macroblock partitions",
            &["p8x8", "b8x8", "i8x8", "i4x4", "p4x4", "all", "none"],
            motion,
            "Combine partition families with commas, or choose all or none.",
            "p8x8,b8x8",
        ),
        choice(
            "b-pyramid",
            "B-frame pyramid",
            &["none", "strict", "normal"],
            motion,
            "Allow B-frames to become references.",
            "normal",
        ),
        number(
            "aq-mode",
            "Adaptive quantization mode",
            0,
            3,
            quant,
            "Shift bits toward blocks that benefit from them.",
            "2",
        ),
        decimal(
            "aq-strength",
            "Adaptive quantization strength",
            0,
            3,
            quant,
            "Strength of block-level bit redistribution.",
            "1.0",
        ),
        native(spec(
            "psy-rd",
            "Psycho-visual RD",
            (0, 10),
            ValueKind::PairDecimal,
            &[],
            quant,
            (
                "RD and trellis texture biases, separated by a colon.",
                "1.0:0.15",
            ),
        )),
        number(
            "trellis",
            "Trellis quantization",
            0,
            2,
            quant,
            "Search quantized coefficients by rate and distortion.",
            "1",
        ),
        decimal(
            "qcomp",
            "QP curve compression",
            0,
            1,
            quant,
            "Balance steady quality against bit allocation across scenes.",
            "0.60",
        ),
        number(
            "chroma-qp-offset",
            "Chroma QP offset",
            -12,
            12,
            quant,
            "Negative values reserve more bits for color.",
            "-2",
        ),
        number(
            "nr",
            "Encoder noise reduction",
            0,
            100000,
            quant,
            "Reduce source noise before coding; can remove fine detail.",
            "0",
        ),
        number(
            "vbv-maxrate",
            "VBV peak rate (kbit/s)",
            0,
            1000000,
            rate,
            "Constrain local peak bitrate with a VBV buffer.",
            "5000",
        ),
        number(
            "vbv-bufsize",
            "VBV buffer (kbit)",
            0,
            1000000,
            rate,
            "Decoder buffer size for a peak-rate limit.",
            "10000",
        ),
        number(
            "qpmin",
            "Minimum QP",
            0,
            81,
            rate,
            "Best quantizer allowed by rate control.",
            "0",
        ),
        number(
            "qpmax",
            "Maximum QP",
            0,
            81,
            rate,
            "Worst quantizer allowed by rate control.",
            "69",
        ),
        number(
            "qpstep",
            "Maximum QP step",
            0,
            81,
            rate,
            "Largest adjacent-frame quantizer change.",
            "4",
        ),
        decimal(
            "ipratio",
            "I-to-P QP ratio",
            1,
            10,
            rate,
            "I-frame quantizer ratio; must be above 1.0.",
            "1.40",
        ),
        decimal(
            "pbratio",
            "P-to-B QP ratio",
            1,
            10,
            rate,
            "B-frame quantizer ratio; must be above 1.0.",
            "1.30",
        ),
        decimal(
            "crf-max",
            "Maximum CRF with VBV",
            0,
            51,
            rate,
            "Worst CRF permitted when VBV limits are active.",
            "35.0",
        ),
    ]
}

pub(super) fn svt() -> Vec<Spec> {
    let visual = "Visual quality";
    let quant = "Quantization and bit allocation";
    let rate = "Rate control";
    let filter = "Filtering";
    let grain = "Film grain and noise";
    let tools = "Encoding tools";
    vec![
        number(
            "tune",
            "Tune",
            0,
            5,
            visual,
            "Select the encoder's quality model; meanings can vary by build.",
            "0",
        ),
        number(
            "aq-mode",
            "Adaptive quantization mode",
            0,
            2,
            quant,
            "Redistribute bits across visually different blocks.",
            "2",
        ),
        decimal(
            "ac-bias",
            "Texture bias",
            0,
            8,
            visual,
            "Preserve texture in rate-distortion decisions.",
            "1.5",
        ),
        number(
            "tx-bias",
            "Transform bias",
            0,
            3,
            visual,
            "Prefer sharper prediction and transform choices.",
            "1",
        ),
        number(
            "sharpness",
            "Sharpness",
            -7,
            7,
            visual,
            "Adjust deblocking and coefficient retention.",
            "2",
        ),
        number(
            "sharp-tx",
            "Sharp transforms",
            0,
            1,
            visual,
            "Retain fine transform coefficients.",
            "1",
        ),
        choice(
            "max-tx-size",
            "Maximum transform size",
            &["32", "64"],
            visual,
            "Smaller transforms can retain fine texture.",
            "32",
        ),
        number(
            "alt-ssim-tuning",
            "Alternative SSIM tuning",
            0,
            1,
            visual,
            "Alternate decisions when SSIM tune is selected.",
            "1",
        ),
        number(
            "complex-hvs",
            "Complex visual model",
            0,
            1,
            visual,
            "Use a slower perceptual detail model.",
            "1",
        ),
        number(
            "variance-boost-strength",
            "Variance boost strength",
            1,
            4,
            quant,
            "Bit boost for low-contrast blocks.",
            "2",
        ),
        number(
            "variance-octile",
            "Variance octile",
            1,
            8,
            quant,
            "Threshold for low-contrast block detection.",
            "5",
        ),
        number(
            "variance-boost-curve",
            "Variance boost curve",
            0,
            3,
            quant,
            "Shape of low-contrast bit allocation.",
            "0",
        ),
        decimal(
            "qp-scale-compress-strength",
            "QP scale compression",
            0,
            8,
            quant,
            "Even out quality across temporal layers.",
            "1.0",
        ),
        number(
            "luminance-qp-bias",
            "Luminance QP bias",
            0,
            100,
            quant,
            "Allocate more bits to dark frames.",
            "10",
        ),
        number(
            "chroma-qm-min",
            "Minimum chroma QM",
            0,
            15,
            quant,
            "Lower chroma quantization-matrix limit.",
            "8",
        ),
        number(
            "chroma-qm-max",
            "Maximum chroma QM",
            0,
            15,
            quant,
            "Upper chroma quantization-matrix limit.",
            "15",
        ),
        number(
            "hbd-mds",
            "High-bit-depth mode decision",
            0,
            2,
            quant,
            "Choose high-bit-depth mode-decision depth. Modes 1 and 2 have no effect with 8-bit output.",
            "1",
        ),
        number(
            "enable-qm",
            "Quantization matrices",
            0,
            1,
            quant,
            "Enable per-frequency quantization matrices.",
            "1",
        ),
        number(
            "qm-min",
            "Minimum luma QM",
            0,
            15,
            quant,
            "Lower luma matrix limit.",
            "6",
        ),
        number(
            "qm-max",
            "Maximum luma QM",
            0,
            15,
            quant,
            "Upper luma matrix limit.",
            "10",
        ),
        number(
            "enable-variance-boost",
            "Variance boost",
            0,
            1,
            quant,
            "Enable low-contrast bit allocation.",
            "1",
        ),
        number(
            "min-qp",
            "Minimum QP",
            0,
            63,
            rate,
            "Best quantizer allowed.",
            "0",
        ),
        number(
            "max-qp",
            "Maximum QP",
            0,
            63,
            rate,
            "Worst quantizer allowed.",
            "63",
        ),
        number(
            "startup-qp-offset",
            "Opening GOP QP offset",
            -63,
            63,
            rate,
            "Shift the opening GOP quantizer.",
            "0",
        ),
        number(
            "enable-dlf",
            "Deblocking filter",
            0,
            2,
            filter,
            "Control in-loop deblocking.",
            "1",
        ),
        number(
            "enable-tf",
            "Temporal filtering",
            0,
            2,
            filter,
            "Filter alternate reference frames.",
            "0",
        ),
        number(
            "tf-strength",
            "Temporal filter strength",
            0,
            4,
            filter,
            "Strength of alternate-reference filtering.",
            "1",
        ),
        number(
            "kf-tf-strength",
            "Keyframe filter strength",
            0,
            4,
            filter,
            "Strength of keyframe temporal filtering.",
            "1",
        ),
        number(
            "noise-adaptive-filtering",
            "Noise-adaptive filtering",
            0,
            4,
            filter,
            "Reduce filtering of noisy source regions.",
            "2",
        ),
        number(
            "cdef-scaling",
            "CDEF scale",
            1,
            30,
            filter,
            "Scale directional enhancement strength.",
            "15",
        ),
        number(
            "enable-cdef",
            "CDEF",
            0,
            1,
            filter,
            "Control directional edge filtering.",
            "1",
        ),
        number(
            "enable-restoration",
            "Loop restoration",
            0,
            1,
            filter,
            "Control post-CDEF loop restoration.",
            "1",
        ),
        number(
            "noise",
            "Synthetic luma grain",
            0,
            200,
            grain,
            "Add in-encoder luma grain synthesis. Use separately from film-grain analysis or a grain table.",
            "50",
        ),
        number(
            "noise-chroma",
            "Synthetic chroma grain",
            -1,
            200,
            grain,
            "Chroma grain strength; -1 follows luma.",
            "-1",
        ),
        number(
            "noise-chroma-from-luma",
            "Chroma from luma",
            0,
            1,
            grain,
            "Derive chroma grain from luma.",
            "0",
        ),
        number(
            "noise-size",
            "Grain particle size",
            -1,
            13,
            grain,
            "Synthetic grain size; -1 follows resolution.",
            "-1",
        ),
        number(
            "noise-norm-strength",
            "Noise normalization",
            0,
            4,
            grain,
            "Retain fine texture in noisy regions.",
            "1",
        ),
        number(
            "adaptive-film-grain",
            "Adaptive grain blocks",
            0,
            1,
            grain,
            "Scale synthesis blocks with resolution.",
            "1",
        ),
        number(
            "scm",
            "Screen-content mode",
            0,
            3,
            tools,
            "Detect palette-friendly and synthetic content.",
            "2",
        ),
        number(
            "fast-decode",
            "Fast decoding",
            0,
            2,
            tools,
            "Avoid coding tools expensive to decode.",
            "1",
        ),
        number(
            "enable-overlays",
            "Overlay frames",
            0,
            1,
            tools,
            "Insert overlay reference pictures.",
            "0",
        ),
        number(
            "lookahead",
            "Lookahead frames",
            0,
            120,
            tools,
            "Set encoder decision lookahead.",
            "40",
        ),
        number(
            "hierarchical-levels",
            "Hierarchical prediction levels",
            3,
            5,
            tools,
            "Set temporal prediction hierarchy.",
            "4",
        ),
    ]
}
