// Offline request validation mirrors the bounded native catalogs. The installed
// binary catalog remains authoritative when editing or executing a request.
import type { EncoderParameterSpec } from '$lib/ipc/generated';

export const extraEncoderParameters: Record<string, EncoderParameterSpec[]> = Object.fromEntries(
  Object.entries({
    x265Standalone: [
      {
        name: 'keyint',
        label: 'Maximum keyframe interval',
        minimum: 1,
        maximum: 10000,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tune',
        label: 'Tuning',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['psnr', 'ssim', 'grain', 'zerolatency', 'fastdecode', 'animation'],
      },
      {
        name: 'profile',
        label: 'Profile',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: [
          'main',
          'main10',
          'main12',
          'mainstillpicture',
          'main-intra',
          'main10-intra',
          'main12-intra',
          'main422-10',
          'main422-12',
          'main422-10-intra',
          'main422-12-intra',
          'main444-8',
          'main444-10',
          'main444-12',
          'main444-intra',
          'main444-10-intra',
          'main444-12-intra',
          'main444-stillpicture',
        ],
      },
      {
        name: 'level-idc',
        label: 'Minimum decoder level',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: [
          '0',
          '1',
          '2',
          '2.1',
          '3',
          '3.1',
          '4',
          '4.1',
          '5',
          '5.1',
          '5.2',
          '6',
          '6.1',
          '6.2',
          '10',
          '20',
          '21',
          '30',
          '31',
          '40',
          '41',
          '50',
          '51',
          '52',
          '60',
          '61',
          '62',
        ],
      },
      {
        name: 'deblock',
        label: 'Deblocking offsets',
        minimum: -6,
        maximum: 6,
        valueKind: 'pairWhole',
        choices: [],
      },
      {
        name: 'selective-sao',
        label: 'Selective sample adaptive offset',
        minimum: 0,
        maximum: 4,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'bframes',
        label: 'Maximum consecutive B-frames',
        minimum: 0,
        maximum: 16,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'b-adapt',
        label: 'B-frame adaptation',
        minimum: 0,
        maximum: 2,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'ref',
        label: 'Reference frames',
        minimum: 1,
        maximum: 8,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'rc-lookahead',
        label: 'Lookahead frames',
        minimum: 0,
        maximum: 250,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'subme',
        label: 'Subpixel motion search',
        minimum: 0,
        maximum: 7,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'merange',
        label: 'Motion search range',
        minimum: 0,
        maximum: 32767,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'me',
        label: 'Motion search method',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['dia', 'hex', 'umh', 'star', 'sea', 'full'],
      },
      {
        name: 'max-merge',
        label: 'Merge candidates',
        minimum: 1,
        maximum: 5,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'limit-refs',
        label: 'Reference limiting',
        minimum: 0,
        maximum: 3,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'bframe-bias',
        label: 'B-frame bias',
        minimum: -90,
        maximum: 100,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'aq-mode',
        label: 'Adaptive quantization mode',
        minimum: 0,
        maximum: 4,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'aq-strength',
        label: 'Adaptive quantization strength',
        minimum: 0,
        maximum: 3,
        valueKind: 'decimal',
        choices: [],
      },
      {
        name: 'psy-rd',
        label: 'Psychovisual rate distortion',
        minimum: 0,
        maximum: 5,
        valueKind: 'decimal',
        choices: [],
      },
      {
        name: 'psy-rdoq',
        label: 'Psychovisual quantization',
        minimum: 0,
        maximum: 50,
        valueKind: 'decimal',
        choices: [],
      },
      {
        name: 'rd',
        label: 'Rate distortion level',
        minimum: 1,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'qcomp',
        label: 'Quantizer curve compression',
        minimum: 0,
        maximum: 1,
        valueKind: 'decimal',
        choices: [],
      },
      {
        name: 'rdoq-level',
        label: 'Quantization optimization level',
        minimum: 0,
        maximum: 2,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'cbqpoffs',
        label: 'Cb quantizer offset',
        minimum: -12,
        maximum: 12,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'crqpoffs',
        label: 'Cr quantizer offset',
        minimum: -12,
        maximum: 12,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'ctu',
        label: 'Coding tree unit size',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['16', '32', '64'],
      },
      {
        name: 'min-cu-size',
        label: 'Minimum coding unit size',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['8', '16', '32'],
      },
      {
        name: 'tu-intra-depth',
        label: 'Intra transform depth',
        minimum: 1,
        maximum: 4,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tu-inter-depth',
        label: 'Inter transform depth',
        minimum: 1,
        maximum: 4,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'rdpenalty',
        label: 'Intra rate distortion penalty',
        minimum: 0,
        maximum: 2,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'qpmin',
        label: 'Minimum quantizer',
        minimum: 0,
        maximum: 69,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'qpmax',
        label: 'Maximum quantizer',
        minimum: 0,
        maximum: 69,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'ipratio',
        label: 'I/P quantizer ratio',
        example: '1.40',
        minimum: 1,
        maximum: 10,
        valueKind: 'decimal',
        choices: [],
      },
      {
        name: 'pbratio',
        label: 'P/B quantizer ratio',
        example: '1.30',
        minimum: 1,
        maximum: 10,
        valueKind: 'decimal',
        choices: [],
      },
      {
        name: 'sao',
        label: 'Sample adaptive offset (0 off, 1 on)',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'cutree',
        label: 'CU-tree rate control (0 off, 1 on)',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
    ],
    aomAv1: [
      {
        name: 'disable-kf',
        label: 'Disable automatic keyframes',
        minimum: 1,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'kf-min-dist',
        label: 'Minimum keyframe interval',
        minimum: 0,
        maximum: 10000,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'kf-max-dist',
        label: 'Maximum keyframe interval',
        minimum: 1,
        maximum: 10000,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tile-rows',
        label: 'Tile rows (log2)',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tile-columns',
        label: 'Tile columns (log2)',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tune-content',
        label: 'Content tuning',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['default', 'screen', 'film'],
      },
      {
        name: 'aq-mode',
        label: 'Adaptive quantization mode',
        minimum: 0,
        maximum: 3,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'enable-qm',
        label: 'Quantization matrices',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'quant-b-adapt',
        label: 'Quantizer adaptation',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tune',
        label: 'Metric tuning',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['psnr', 'ssim', 'iq', 'ssimulacra2'],
      },
      {
        name: 'qm-min',
        label: 'Minimum quantization matrix',
        minimum: 0,
        maximum: 15,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'qm-max',
        label: 'Maximum quantization matrix',
        minimum: 0,
        maximum: 15,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'sharpness',
        label: 'Sharpness',
        minimum: 0,
        maximum: 7,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'deltaq-mode',
        label: 'Delta quantization mode',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'enable-chroma-deltaq',
        label: 'Chroma delta quantization',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'enable-cdef',
        label: 'Directional enhancement filter',
        minimum: 0,
        maximum: 3,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'arnr-maxframes',
        label: 'Maximum temporal filter frames',
        minimum: 0,
        maximum: 15,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'arnr-strength',
        label: 'Temporal filter strength',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'enable-keyframe-filtering',
        label: 'Keyframe filtering',
        minimum: 0,
        maximum: 2,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'enable-restoration',
        label: 'Loop restoration',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'lag-in-frames',
        label: 'Lookahead frames',
        minimum: 0,
        maximum: 48,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'mv-cost-upd-freq',
        label: 'Motion cost update frequency',
        minimum: 0,
        maximum: 3,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'enable-fwd-kf',
        label: 'Forward keyframes',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'min-q',
        label: 'Minimum quantizer',
        minimum: 0,
        maximum: 63,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'max-q',
        label: 'Maximum quantizer',
        minimum: 0,
        maximum: 63,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'undershoot-pct',
        label: 'Rate control undershoot',
        minimum: 0,
        maximum: 100,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'overshoot-pct',
        label: 'Rate control overshoot',
        minimum: 0,
        maximum: 100,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'auto-alt-ref',
        label: 'Alternate reference frames',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
    ],
    vpxStandalone: [
      {
        name: 'kf-max-dist',
        label: 'Maximum keyframe interval',
        minimum: 1,
        maximum: 10000,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tile-rows',
        label: 'Tile rows (log2)',
        minimum: 0,
        maximum: 2,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tile-columns',
        label: 'Tile columns (log2)',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'tune',
        label: 'Metric tuning',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['psnr', 'ssim'],
      },
      {
        name: 'tune-content',
        label: 'Content tuning',
        minimum: 0,
        maximum: 0,
        valueKind: 'choice',
        choices: ['default', 'screen', 'film'],
      },
      {
        name: 'sharpness',
        label: 'Sharpness',
        minimum: 0,
        maximum: 7,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'static-thresh',
        label: 'Static block threshold',
        minimum: 0,
        maximum: 65535,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'frame-boost',
        label: 'Frame boost',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'noise-sensitivity',
        label: 'Noise sensitivity',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'auto-alt-ref',
        label: 'Alternate reference frames',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'lag-in-frames',
        label: 'Lookahead frames',
        minimum: 0,
        maximum: 25,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'arnr-maxframes',
        label: 'Maximum temporal filter frames',
        minimum: 0,
        maximum: 15,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'arnr-strength',
        label: 'Temporal filter strength',
        minimum: 0,
        maximum: 6,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'alt-ref-aq',
        label: 'Alternate reference quantization',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'frame-parallel',
        label: 'Frame parallel decoding',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'aq-mode',
        label: 'Adaptive quantization mode',
        minimum: 0,
        maximum: 4,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'min-q',
        label: 'Minimum quantizer',
        minimum: 0,
        maximum: 63,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'max-q',
        label: 'Maximum quantizer',
        minimum: 0,
        maximum: 63,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'enable-tpl',
        label: 'Temporal dependency model',
        minimum: 0,
        maximum: 1,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'corpus-complexity',
        label: 'Corpus complexity',
        minimum: 0,
        maximum: 10000,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'undershoot-pct',
        label: 'Rate control undershoot',
        minimum: 0,
        maximum: 100,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'overshoot-pct',
        label: 'Rate control overshoot',
        minimum: 0,
        maximum: 100,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'bias-pct',
        label: 'Rate control bias',
        minimum: 0,
        maximum: 100,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'minsection-pct',
        label: 'Minimum section rate',
        minimum: 0,
        maximum: 100,
        valueKind: 'whole',
        choices: [],
      },
      {
        name: 'maxsection-pct',
        label: 'Maximum section rate',
        minimum: 0,
        maximum: 65535,
        valueKind: 'whole',
        choices: [],
      },
    ],
  }).map(([encoder, specs]) => [
    encoder,
    specs.map((spec) => ({
      ...spec,
      argument: `--${spec.name}`,
      minimumValue: String(spec.minimum),
      maximumValue: String(spec.maximum),
      group: 'Advanced',
      description: '',
      example: 'example' in spec ? spec.example || '' : '',
    })),
  ]),
);
