// Generated by media-core. Run pnpm contracts; do not edit.

export type ToolInfo = { id: string, name: string, available: boolean, path: string | null, version: string | null, detail: string | null, };

export type MediaStream = {
/**
 * Original source stream index, independent of presentation order.
 */
index: number, kind: string, codec: string | null, width: number | null, height: number | null,
/**
 * Original rational frame rate, for example `24000/1001`.
 */
frameRate: string | null, sampleRate: number | null, channels: number | null, language: string | null, title: string | null, pixelFormat?: string | null, bitDepth?: number | null, colorPrimaries?: string | null, colorTransfer?: string | null, colorSpace?: string | null, colorRange?: string | null,
/**
 * HDR transfer family; this does not establish encode compatibility.
 */
hdrFormat?: string | null,
/**
 * Whether stream headers report mastering or content light metadata.
 */
hasHdrStaticMetadata?: boolean | null,
/**
 * Formats reported in stream headers; absence does not rule out frame metadata.
 */
dynamicHdrFormats?: Array<string> | null, };

export type MediaFile = {
/**
 * Stable for the same canonical input path; this is not a content hash.
 */
id: string, path: string, name: string,
/**
 * Decimal text preserves byte counts beyond JavaScript's safe integer range.
 */
sizeBytes: string, durationSeconds: number | null, format: string | null, streams: Array<MediaStream>, };

export type AppError = { code: string, message: string, path: string | null, };

export type RemuxRequest = { inputPath: string, outputPath: string, streamIndices: Array<number>, };

export type EncodeBackend = "standalone" | "av1an";

export type VideoEncoder = "svtAv1" | "x264";

export type EncodeSettings = { backend: EncodeBackend, encoder: VideoEncoder, workers: number, videoStreamIndex: number, crf: number, preset: number,
/**
 * AV1 grain synthesis strength; zero leaves synthesis disabled.
 */
filmGrain: number,
/**
 * Explicit consent to discard dynamic HDR metadata for an HDR10 base layer.
 */
hdr10Fallback: boolean, };

export type EncodeRequest = { source: RemuxRequest, settings: EncodeSettings, };

export type JobState = "queued" | "preparing" | "running" | "finalizing" | "succeeded" | "canceling" | "canceled" | "failed" | "interrupted";

export type JobSnapshot = { id: string, state: JobState, request: RemuxRequest, encodeSettings: EncodeSettings | null, progressSeconds: number | null, durationSeconds: number | null, logs: Array<string>, error: AppError | null, logPath: string | null, };

export type FolderScanRequest = { path: string, recursive: boolean, };

export type FolderScanResult = { paths: Array<string>, errors: Array<AppError>, skippedCount: number, truncated: boolean, };

export type BatchEncodeInput = { inputPath: string, streamIndices: Array<number>, videoStreamIndex: number, };

export type BatchEncodeRequest = { backend: EncodeBackend, encoder: VideoEncoder, workers: number, inputs: Array<BatchEncodeInput>, outputDirectory: string, crf: number, preset: number, filmGrain: number, hdr10Fallback: boolean, };

export type BatchEncodeItem = { inputPath: string, outputPath: string | null, request: EncodeRequest | null, error: AppError | null, };

export type BatchEncodePreview = { items: Array<BatchEncodeItem>, };
