"""Build the Linux package FFmpeg pair and retain all linked library sources.

Requires Linux x86-64, Python 3.14+, GCC/G++, make, nasm, cmake, ninja,
autoconf, automake, libtool, pkg-config, patch, git, gperf and xxd. A pinned Meson
source is included. --verify-only can validate
the pinned archives, extracted licenses and local Git source on other hosts.
No package manager is invoked and an existing build directory is never replaced.
"""

import argparse
import base64
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import platform
import posixpath
import re
import shutil
import subprocess
import sys
import tarfile
from urllib.request import Request, urlopen
import uuid

ROOT = Path(__file__).resolve().parents[1]
LOCK = Path(__file__).with_name("package-ffmpeg-linux-lock.json")
TARGET = "x86_64-unknown-linux-gnu"
MAX_ARCHIVE = 512 * 1024 * 1024
# Original test-only block glyphs, generated by tests/fixtures/subtitle-font.py.
SMOKE_FONT = 'AAEAAAAKAIAAAwAgT1MvMkUARHIAAAEoAAAAYGNtYXAAjgHtAAABkAAAAPJnbHlmKUBzgAAAAowAAAAaaGVhZFm3pQAAAACsAAAANmhoZWEFFgH2AAAA5AAAACRobXR4AlgAAAAAAYgAAAAIbG9jYQAAAA0AAAKEAAAACG1heHAABQAGAAABCAAAACBuYW1lyfJakwAAAqgAAAGncG9zdGjVbXEAAARQAAAALgABAAAAAQAAoBZEqF8PPPUAAQPoAAAAAHwlsIAAAAAAfCWwgAAyAAACJgMgAAAAAwACAAAAAAAAAAEAAAMg/zgAAAJYAAAAZAH0AAEAAAAAAAAAAAAAAAAAAAABAAEAAAADAAQAAQAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAwJYAZAABQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAPz8/PwAAACAAfgMg/zgAAAMgAMgAAAAAAAAAAAAAAAAAAAAgAAACWAAAAAAAAAAAAAIAAAADAAAAFAADAAEAAAAUAAQA3gAAAAQABAABAAAAfv//AAAAIP//AAAAAQAEAAAAAQACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAAAAAAAAAAADQABADIAAAImAyAAAwAAMyERITIB9P4MAyAAAAAAAAAMAJYAAQAAAAAAAQAOAAAAAQAAAAAAAgAHAA4AAQAAAAAAAwAQABUAAQAAAAAABAAWACUAAQAAAAAABQALADsAAQAAAAAABgAVAEYAAwABBAkAAQAcAFsAAwABBAkAAgAOAHcAAwABBAkAAwAgAIUAAwABBAkABAAsAKUAAwABBAkABQAWANEAAwABBAkABgAqAOdKZXNzZXMgRml4dHVyZVJlZ3VsYXJKZXNzZXMgRml4dHVyZSAxSmVzc2VzIEZpeHR1cmUgUmVndWxhclZlcnNpb24gMS4wSmVzc2VzRml4dHVyZS1SZWd1bGFyAEoAZQBzAHMAZQBzACAARgBpAHgAdAB1AHIAZQBSAGUAZwB1AGwAYQByAEoAZQBzAHMAZQBzACAARgBpAHgAdAB1AHIAZQAgADEASgBlAHMAcwBlAHMAIABGAGkAeAB0AHUAcgBlACAAUgBlAGcAdQBsAGEAcgBWAGUAcgBzAGkAbwBuACAAMQAuADAASgBlAHMAcwBlAHMARgBpAHgAdAB1AHIAZQAtAFIAZQBnAHUAbABhAHIAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAMBAgVibG9jawAA'
CONFIGURE = [
    "--disable-autodetect", "--disable-doc", "--disable-ffplay", "--disable-debug",
    "--disable-shared", "--enable-static", "--enable-gpl", "--enable-pthreads",
    "--enable-libx264", "--enable-libx265", "--enable-libvpx", "--enable-libopus",
    "--enable-libmp3lame", "--enable-libvorbis", "--enable-libdav1d", "--enable-libzimg",
    "--enable-libass", "--enable-libvmaf",
    "--enable-zlib", "--enable-bzlib", "--enable-lzma", "--pkg-config-flags=--static",
]
# Codec libraries are statically linked. These are standard Linux compiler/C
# runtime dependencies; none may resolve inside the temporary build prefix.
SYSTEM_LIBRARIES = re.compile(
    r"^(?:linux-vdso\.so\.1|ld-linux-x86-64\.so\.2|libc\.so\.6|libm\.so\.6|"
    r"libmvec\.so\.1|libpthread\.so\.0|libdl\.so\.2|librt\.so\.1|libgcc_s\.so\.1|libstdc\+\+\.so\.6)$"
)


def digest(path: Path) -> str:
    with path.open("rb") as source:
        return hashlib.file_digest(source, "sha256").hexdigest()


def relative(value: str) -> PurePosixPath:
    if not value or "\\" in value or ":" in value or "\0" in value:
        raise ValueError(f"Invalid source path: {value!r}")
    path = PurePosixPath(value)
    if path.is_absolute() or ".." in path.parts or not path.parts:
        raise ValueError(f"Invalid source path: {value!r}")
    return path


def download(record: dict, cache: Path) -> Path:
    filename = relative(record["filename"])
    if len(filename.parts) != 1 or not re.fullmatch(r"[a-f0-9]{64}", record["sha256"]):
        raise ValueError("Invalid locked source filename or checksum.")
    destination = cache / filename
    if destination.exists():
        if destination.is_symlink() or not destination.is_file() or digest(destination) != record["sha256"]:
            raise ValueError(f"The cached source checksum differs: {destination}")
        return destination
    if not record["url"].startswith("https://"):
        raise ValueError("Source downloads require HTTPS.")
    temporary = cache / (str(filename) + ".partial-" + uuid.uuid4().hex)
    with urlopen(Request(record["url"], headers={"User-Agent": "jesses-linux-package"}), timeout=90) as response, temporary.open("xb") as output:
        size = 0
        while block := response.read(1024 * 1024):
            size += len(block)
            if size > MAX_ARCHIVE:
                raise ValueError("The source download exceeds its size limit.")
            output.write(block)
    if digest(temporary) != record["sha256"]:
        raise ValueError(f"Source checksum mismatch; retained for inspection: {temporary}")
    # A concurrent downloader cannot replace an existing cached archive.
    os.link(temporary, destination)
    temporary.unlink()
    return destination


def extract(archive: Path, destination: Path, root: str) -> Path:
    """Extract bounded data only; materialize safe internal links as file copies."""
    relative(root)
    destination.mkdir(parents=True, exist_ok=False)
    with tarfile.open(archive) as bundle:
        members = bundle.getmembers()
        if len(members) > 200_000 or sum(item.size for item in members) > 2 * 1024**3:
            raise ValueError("The source archive exceeds extraction bounds.")
        files = {}
        links = []
        directories = []
        for member in members:
            path = relative(member.name)
            if path.parts[0] != root or not (member.isdir() or member.isfile() or member.issym() or member.islnk()):
                raise ValueError(f"Unexpected source archive member: {member.name}")
            if member.isdir():
                directories.append((path, member.mtime))
                continue
            if path.as_posix() in files:
                raise ValueError("The source archive repeats a file path.")
            files[path.as_posix()] = member
            if member.issym() or member.islnk():
                linked = posixpath.normpath(posixpath.join(path.parent.as_posix(), member.linkname)) if member.issym() else member.linkname
                target = relative(linked)
                if target.parts[0] != root:
                    raise ValueError("A source archive link escapes its root.")
                links.append((path, target, member.mtime))
        for path, _ in directories:
            (destination / path).mkdir(parents=True, exist_ok=True)
        for name, member in files.items():
            if not member.isfile():
                continue
            target = destination / relative(name)
            target.parent.mkdir(parents=True, exist_ok=True)
            with bundle.extractfile(member) as source, target.open("xb") as output:
                shutil.copyfileobj(source, output)
            target.chmod(0o755 if member.mode & 0o111 else 0o644)
            os.utime(target, (member.mtime, member.mtime))
        for path, linked, mtime in links:
            source = files.get(linked.as_posix())
            if source is None or not source.isfile():
                raise ValueError("A source archive link must identify a regular member.")
            target = destination / path
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(destination / linked, target)
            os.utime(target, (mtime, mtime))
        for path, mtime in directories:
            os.utime(destination / path, (mtime, mtime))
    result = destination / root
    if not result.is_dir():
        raise ValueError("The expected source directory is absent.")
    return result


def record(path: Path, delivery: Path, **extra) -> dict:
    return {**extra, "path": path.relative_to(delivery).as_posix(), "sha256": digest(path)}


class Builder:
    def __init__(self, directory: Path, cache: Path, jobs: int):
        self.directory = directory.absolute()
        self.directory.mkdir(parents=True, exist_ok=False)
        self.cache = cache.absolute()
        self.cache.mkdir(parents=True, exist_ok=True)
        self.prefix = self.directory / "prefix"
        self.prefix.mkdir()
        self.work = self.directory / "work"
        self.work.mkdir()
        self.delivery = self.directory / "delivery"
        self.delivery.mkdir()
        for name in ("sources", "licenses", "build"):
            (self.delivery / name).mkdir()
        self.jobs = str(jobs)
        self.commands = []
        self.sources = []
        self.licenses = []
        self.patches = {}
        self.meson = ["meson"]
        # Do not inherit optional codec search paths or compiler substitutions.
        self.env = {key: value for key, value in os.environ.items() if key not in {
            "CC", "CXX", "CPP", "AR", "AS", "LD", "NM", "RANLIB", "STRIP", "OBJCOPY", "READELF",
            "CFLAGS", "CXXFLAGS", "CPPFLAGS", "LDFLAGS", "LIBS", "CROSS_COMPILE", "HOSTCC", "CC_FOR_BUILD",
            "CPATH", "C_INCLUDE_PATH", "CPLUS_INCLUDE_PATH", "LIBRARY_PATH", "LD_LIBRARY_PATH", "LD_RUN_PATH",
            "COMPILER_PATH", "GCC_EXEC_PREFIX",
            "LD_PRELOAD", "PKG_CONFIG", "PKG_CONFIG_PATH", "PKG_CONFIG_LIBDIR", "PKG_CONFIG_SYSROOT_DIR",
            "CMAKE_PREFIX_PATH", "CMAKE_TOOLCHAIN_FILE", "CMAKE_GENERATOR", "MAKEFLAGS", "MFLAGS",
            "BASH_ENV", "ENV", "CONFIG_SITE", "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE",
            "PYTHONPATH", "PYTHONHOME", "DESTDIR", "MESON_PACKAGE_CACHE_DIR",
            "GIT_OBJECT_DIRECTORY", "GIT_ALTERNATE_OBJECT_DIRECTORIES", "GIT_TEMPLATE_DIR",
            "GIT_CONFIG", "GIT_CONFIG_PARAMETERS", "GIT_CONFIG_COUNT",
        }}
        self.env.update({
            "CC": "gcc", "CXX": "g++", "AR": "ar", "LC_ALL": "C", "TZ": "UTC",
            "SOURCE_DATE_EPOCH": "1789257600",
            "CFLAGS": "-O2 -fPIC -march=x86-64 -mtune=generic",
            "CXXFLAGS": "-O2 -fPIC -march=x86-64 -mtune=generic",
            "CPPFLAGS": f"-I{self.prefix}/include", "LDFLAGS": f"-L{self.prefix}/lib",
            "PKG_CONFIG_PATH": "", "PKG_CONFIG_LIBDIR": f"{self.prefix}/lib/pkgconfig",
            "GIT_CONFIG_NOSYSTEM": "1", "GIT_CONFIG_GLOBAL": os.devnull, "CONFIG_SITE": os.devnull,
        })

    def run(self, args, cwd=None, timeout=1800, input_text=None, capture=False):
        args = [str(arg) for arg in args]
        cwd = cwd or self.directory
        self.commands.append({"argv": args, "cwd": str(cwd), "stdin": input_text})
        log_path = self.directory / "build.log"
        try:
            with log_path.open("a", encoding="utf-8") as log:
                log.write(json.dumps(self.commands[-1]) + "\n")
                log.flush()
                result = subprocess.run(args, cwd=cwd, env=self.env, input=input_text, text=True, stdout=subprocess.PIPE if capture else log, stderr=subprocess.STDOUT, timeout=timeout, check=True)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
            lines = log_path.read_text(encoding="utf-8", errors="replace").splitlines()
            tail = lines[-100:]
            print(f"Build command failed: {json.dumps(args)}", file=sys.stderr)
            print(f"Last {len(tail)} lines of {log_path}:", file=sys.stderr)
            print("\n".join(tail), file=sys.stderr)
            captured = getattr(error, "stdout", None)
            if captured:
                if isinstance(captured, bytes):
                    captured = captured.decode(errors="replace")
                captured_tail = captured.splitlines()[-100:]
                print(f"Last {len(captured_tail)} captured output lines:", file=sys.stderr)
                print("\n".join(captured_tail), file=sys.stderr)
            raise
        return result.stdout if capture else None

    def source(self, item: dict) -> Path:
        archive = download(item, self.cache)
        packaged = self.delivery / "sources" / item["filename"]
        shutil.copy2(archive, packaged)
        self.sources.append(record(packaged, self.delivery, url=item["url"]))
        if "bundleRoot" not in item:
            source = extract(archive, self.work / "ffmpeg", item["sourceRoot"])
        else:
            bundle = extract(archive, self.work / (item["id"] + "-bundle"), item["bundleRoot"])
            container = bundle.parent
            if "embeddedArchive" in item:
                embedded = container / relative(item["embeddedArchive"])
                if digest(embedded) != item["embeddedSha256"]:
                    raise ValueError("An embedded upstream source checksum differs.")
                source = extract(embedded, self.work / item["id"], item["sourceRoot"])
            else:
                bare = container / relative(item["gitDirectory"])
                source = self.work / item["id"]
                self.run(["git", "clone", "--no-checkout", "--no-hardlinks", "--local", bare, source], timeout=120)
                self.run(["git", "-C", source, "checkout", "--detach", item["gitCommit"]], timeout=120)
                if self.run(["git", "-C", source, "rev-parse", "HEAD"], capture=True).strip() != item["gitCommit"]:
                    raise ValueError("The extracted local Git source has a different revision.")
            for patch in item.get("patches", []):
                path = container / relative(patch["path"])
                if digest(path) != patch["sha256"]:
                    raise ValueError("The source patch checksum differs.")
                self.patches.setdefault(item["id"], []).append(path)
        identifier = item.get("id", "ffmpeg")
        licenses = self.delivery / "licenses" / identifier
        licenses.mkdir()
        for name in item["licenseFiles"]:
            original = source / relative(name)
            target = licenses / name.replace("/", "-")
            if not original.is_file() or original.stat().st_size > 1024 * 1024:
                raise ValueError(f"Missing or oversized license: {identifier}/{name}")
            shutil.copy2(original, target)
            self.licenses.append(record(target, self.delivery))
        print(f"Verified source and licenses: {identifier}", flush=True)
        return source

    def make(self, source, *targets):
        self.run(["make", f"-j{self.jobs}", *targets], cwd=source)

    def autotools(self, source, *options):
        self.run([source / "configure", f"--prefix={self.prefix}", "--libdir=" + str(self.prefix / "lib"), "--disable-shared", "--enable-static", *options], cwd=source, timeout=300)
        self.make(source)
        self.make(source, "install")

    def library(self, identifier: str, source: Path):
        print(f"Building static library: {identifier}", flush=True)
        for patch in self.patches.get(identifier, []):
            self.run(["patch", "-p1", "--batch", "--forward", "-i", patch], cwd=source, timeout=30)
        if identifier == "bzip2":
            self.make(source, "libbz2.a", f"CFLAGS={self.env['CFLAGS']}")
            (self.prefix / "include").mkdir(exist_ok=True)
            (self.prefix / "lib").mkdir(exist_ok=True)
            shutil.copy2(source / "bzlib.h", self.prefix / "include/bzlib.h")
            shutil.copy2(source / "libbz2.a", self.prefix / "lib/libbz2.a")
        elif identifier == "zlib":
            self.run([source / "configure", f"--prefix={self.prefix}", "--static"], cwd=source, timeout=300)
            self.make(source)
            self.make(source, "install")
        elif identifier == "xz":
            self.autotools(source, "--disable-doc", "--disable-nls", "--disable-xz", "--disable-xzdec", "--disable-lzmadec", "--disable-lzmainfo", "--disable-scripts")
        elif identifier == "lame":
            self.autotools(source, "--disable-frontend", "--disable-decoder", "--without-libiconv")
        elif identifier in {"libogg", "libvorbis"}:
            self.autotools(source, "--disable-docs")
        elif identifier == "opus":
            self.autotools(source, "--disable-doc", "--disable-extra-programs")
        elif identifier == "zimg":
            self.run(["sh", "autogen.sh"], cwd=source, timeout=300)
            self.autotools(source)
        elif identifier == "x264":
            self.run([source / "configure", f"--prefix={self.prefix}", "--enable-static", "--enable-pic", "--disable-cli", "--disable-opencl"], cwd=source, timeout=300)
            self.make(source)
            self.make(source, "install")
        elif identifier == "libvpx":
            self.run([source / "configure", f"--prefix={self.prefix}", "--target=x86_64-linux-gcc", "--enable-static", "--disable-shared", "--enable-pic", "--enable-vp9-highbitdepth", "--disable-examples", "--disable-tools", "--disable-unit-tests", "--disable-docs"], cwd=source, timeout=300)
            self.make(source)
            self.make(source, "install")
        elif identifier == "dav1d":
            self.meson_build(identifier, source, "-Denable_tools=false", "-Denable_tests=false")
        elif identifier == "expat":
            build = self.work / "expat-build"
            self.run(["cmake", "-S", source, "-B", build, "-G", "Ninja", f"-DCMAKE_INSTALL_PREFIX={self.prefix}", "-DCMAKE_INSTALL_LIBDIR=lib", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_POSITION_INDEPENDENT_CODE=ON", "-DEXPAT_SHARED_LIBS=OFF", "-DEXPAT_BUILD_TOOLS=OFF", "-DEXPAT_BUILD_EXAMPLES=OFF", "-DEXPAT_BUILD_TESTS=OFF", "-DEXPAT_BUILD_DOCS=OFF", "-DEXPAT_BUILD_FUZZERS=OFF"], timeout=300)
            self.run(["cmake", "--build", build, "--parallel", self.jobs])
            self.run(["cmake", "--install", build])
        elif identifier == "freetype":
            self.meson_build(identifier, source, "-Dzlib=system", "-Dbzip2=enabled", "-Dbrotli=enabled", "-Dpng=enabled", "-Dharfbuzz=disabled", "-Dtests=disabled")
        elif identifier in {"brotli", "libpng"}:
            build = self.work / f"{identifier}-build"
            options = ["-DBUILD_SHARED_LIBS=OFF", "-DBROTLI_DISABLE_TESTS=ON"] if identifier == "brotli" else ["-DPNG_SHARED=OFF", "-DPNG_STATIC=ON", "-DPNG_TESTS=OFF", "-DPNG_TOOLS=OFF", "-DPNG_EXECUTABLES=OFF", f"-DZLIB_LIBRARY={self.prefix}/lib/libz.a", f"-DZLIB_INCLUDE_DIR={self.prefix}/include"]
            self.run(["cmake", "-S", source, "-B", build, "-G", "Ninja", f"-DCMAKE_INSTALL_PREFIX={self.prefix}", "-DCMAKE_INSTALL_LIBDIR=lib", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_POSITION_INDEPENDENT_CODE=ON", *options], timeout=300)
            self.run(["cmake", "--build", build, "--parallel", self.jobs])
            self.run(["cmake", "--install", build])
        elif identifier == "harfbuzz":
            self.meson_build(identifier, source, "-Dfreetype=enabled", "-Dzlib=enabled", *[f"-D{feature}=disabled" for feature in ("glib", "gobject", "cairo", "chafa", "png", "icu", "graphite", "graphite2", "fontations", "gdi", "directwrite", "coretext", "harfrust", "kbts", "wasm", "raster", "vector", "gpu", "gpu_demo", "subset", "tests", "introspection", "docs", "utilities", "benchmark")])
        elif identifier == "fribidi":
            self.meson_build(identifier, source, "-Ddocs=false", "-Dbin=false", "-Dtests=false")
        elif identifier == "fontconfig":
            # Compile standard system font/config search paths, while installing
            # through DESTDIR so this unprivileged build never writes /etc.
            self.meson_build(identifier, source, "-Dxml-backend=expat", "-Ddoc=disabled", "-Dnls=disabled", "-Dtests=disabled", "-Dtests-external-fonts=disabled", "-Dtools=disabled", "-Dcache-build=disabled", "-Diconv=disabled", "-Dfontations=disabled", "-Dbaseconfig-dir=/etc/fonts", "-Dconfig-dir=/etc/fonts/conf.d", "-Dtemplate-dir=/usr/share/fontconfig/conf.avail", "-Dcache-dir=/var/cache/fontconfig", staged=True)
        elif identifier == "libunibreak":
            self.run(["autoreconf", "-fi"], cwd=source, timeout=300)
            self.autotools(source)
        elif identifier == "libass":
            self.meson_build(identifier, source, "-Dfontconfig=enabled", "-Dlibunibreak=enabled", "-Dasm=enabled", "-Ddirectwrite=disabled", "-Dcoretext=disabled", "-Drequire-system-font-provider=true")
        elif identifier == "vmaf":
            self.run(["xxd", "-v"], capture=True, timeout=20)
            self.meson_build(identifier, source / "libvmaf", "-Denable_tests=false", "-Denable_docs=false", "-Denable_tools=false", "-Dbuilt_in_models=true", "-Denable_cuda=false", "-Denable_nvtx=false")
            pc = self.prefix / "lib/pkgconfig/libvmaf.pc"
            contents = pc.read_text(encoding="utf-8")
            # VMAF 3.2 uses C++ for its model parser, but the generated static pc
            # file can omit the C++ runtime. Record this repair in the recipe.
            if "Libs.private:" in contents:
                contents = contents.replace("Libs.private:", "Libs.private: -lstdc++", 1)
            else:
                contents += "\nLibs.private: -lstdc++\n"
            pc.write_text(contents, encoding="utf-8")
        elif identifier == "x265":
            self.x265(source)
        else:
            raise ValueError(f"No locked build recipe for {identifier}")

    def meson_build(self, identifier, source, *options, staged=False):
        build = self.work / f"{identifier}-build"
        self.run([*self.meson, "setup", build, source, f"--prefix={self.prefix}", "--libdir=lib", "--default-library=static", "--buildtype=release", "--wrap-mode=nodownload", "--auto-features=disabled", "-Db_staticpic=true", *options], timeout=300)
        self.run([*self.meson, "compile", "-C", build, "-j", self.jobs])
        if staged:
            stage = self.work / f"{identifier}-stage"
            self.run([*self.meson, "install", "-C", build, "--destdir", stage])
            installed = stage / self.prefix.relative_to(self.prefix.anchor)
            shutil.copytree(installed, self.prefix, dirs_exist_ok=True)
        else:
            self.run([*self.meson, "install", "-C", build])

    def x265(self, source):
        common = ["-G", "Ninja", f"-DCMAKE_INSTALL_PREFIX={self.prefix}", "-DCMAKE_BUILD_TYPE=Release", "-DNATIVE_BUILD=OFF", "-DENABLE_SHARED=OFF", "-DENABLE_CLI=OFF", "-DENABLE_LIBNUMA=OFF", "-DENABLE_HDR10_PLUS=OFF", "-DENABLE_PIC=ON", "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"]
        builds = {depth: self.work / f"x265-{depth}" for depth in (8, 10, 12)}
        for depth in (12, 10):
            self.run(["cmake", "-S", source / "source", "-B", builds[depth], *common, "-DHIGH_BIT_DEPTH=ON", "-DEXPORT_C_API=OFF", f"-DMAIN12={'ON' if depth == 12 else 'OFF'}"], timeout=300)
            self.run(["cmake", "--build", builds[depth], "--parallel", self.jobs])
        builds[8].mkdir()
        for depth in (10, 12):
            shutil.copy2(builds[depth] / "libx265.a", builds[8] / f"libx265_main{depth}.a")
        self.run(["cmake", "-S", source / "source", "-B", builds[8], *common, "-DLINKED_10BIT=ON", "-DLINKED_12BIT=ON", "-DEXTRA_LIB=x265_main10.a;x265_main12.a", "-DEXTRA_LINK_FLAGS=-L."], timeout=300)
        self.run(["cmake", "--build", builds[8], "--parallel", self.jobs])
        (builds[8] / "libx265.a").rename(builds[8] / "libx265_main.a")
        self.run(["ar", "-M"], cwd=builds[8], input_text="CREATE libx265.a\nADDLIB libx265_main.a\nADDLIB libx265_main10.a\nADDLIB libx265_main12.a\nSAVE\nEND\n")
        self.run(["cmake", "--install", builds[8]])

    def ffmpeg(self, source, version):
        if list(self.prefix.rglob("*.so*")):
            raise ValueError("The codec prefix unexpectedly contains shared libraries.")
        flags = [*CONFIGURE, f"--extra-cflags=-I{self.prefix}/include", f"--extra-ldflags=-L{self.prefix}/lib", "--extra-libs=-lstdc++ -lm -lpthread"]
        self.run([source / "configure", *flags], cwd=source, timeout=600)
        self.make(source, "ffmpeg", "ffprobe")
        tools = []
        for name in ("ffmpeg", "ffprobe"):
            target = self.delivery / name
            shutil.copy2(source / name, target)
            target.chmod(0o755)
            identity = self.run([target, "-version"], capture=True, timeout=20).splitlines()[0]
            if not identity.startswith(f"{name} version {version} "):
                raise ValueError(f"Unexpected {name} release: {identity}")
            dependencies = self.run(["ldd", target], capture=True, timeout=20)
            validate_dependencies(dependencies, self.prefix)
            (self.delivery / "build" / f"{name}-ldd.txt").write_text(dependencies, encoding="utf-8")
            tools.append(record(target, self.delivery, id=name, version=identity))
        # These are actual short encodes and display conversion; a name alone is not
        # enough to establish multidepth library linkage or HDR display support.
        self.smoke(self.delivery / "ffmpeg")
        return tools, flags

    def smoke(self, ffmpeg):
        base = [ffmpeg, "-v", "error", "-nostdin", "-f", "lavfi", "-i"]
        for depth in (8, 10, 12):
            self.run([*base, "testsrc2=s=64x64:r=4:d=1", "-vf", f"format=yuv420p{str(depth) + 'le' if depth > 8 else ''}", "-c:v", "libx265", "-preset", "ultrafast", "-x265-params", "pools=1:frame-threads=1", "-f", "null", "-"], timeout=60)
        for codec in ("libx264", "libvpx-vp9"):
            self.run([*base, "testsrc2=s=64x64:r=4:d=1", "-c:v", codec, "-f", "null", "-"], timeout=60)
        for codec, extra in [("aac", []), ("libopus", []), ("libmp3lame", []), ("libvorbis", ["-q:a", "3"]), ("ac3", []), ("eac3", []), ("flac", [])]:
            self.run([*base, "sine=sample_rate=48000:duration=0.1", "-c:a", codec, *extra, "-f", "null", "-"], timeout=30)
        self.run([*base, "color=c=white:s=64x64:d=0.1", "-vf", "format=yuv420p10le,setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,zscale=transfer=linear:npl=100,format=gbrpf32le,zscale=primaries=bt709,tonemap=tonemap=hable:desat=0,zscale=transfer=iec61966-2-1:matrix=gbr:range=full,format=rgb24", "-frames:v", "1", "-f", "null", "-"], timeout=30)
        # Loading a real built-in model detects source builds without xxd; those
        # can otherwise silently install a library containing no model data.
        model = self.work / "vmaf-smoke.json"
        self.run([*base, "testsrc2=s=192x108:r=4:d=1", "-filter_complex", "split[a][b];[a][b]libvmaf=model=version=vmaf_v0.6.1:log_fmt=json:log_path=vmaf-smoke.json", "-f", "null", "-"], cwd=self.work, timeout=60)
        score = json.loads(model.read_text(encoding="utf-8"))["pooled_metrics"]["vmaf"]["mean"]
        if not 99 <= score <= 101:
            raise ValueError("The built-in VMAF model did not measure the identical reference.")
        # An original geometric font makes this gate independent of host fonts.
        font = self.work / "smoke-font.ttf"
        font.write_bytes(base64.b64decode(SMOKE_FONT))
        captions = self.work / "smoke.ass"
        captions.write_text("[Script Info]\nScriptType: v4.00+\nPlayResX: 64\nPlayResY: 64\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Jesses Fixture,30,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,1,1,1,1\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,AA\n", encoding="utf-8")
        pixels = self.work / "libass-smoke.gray"
        self.run([*base, "color=c=black:s=64x64:d=0.1", "-vf", "subtitles=filename=smoke.ass:fontsdir=.", "-frames:v", "1", "-pix_fmt", "gray", "-f", "rawvideo", "-n", pixels], cwd=self.work, timeout=30)
        data = pixels.read_bytes()
        if len(data) != 4096 or sum(value > 220 for value in data) < 100:
            raise ValueError("libass did not render the embedded geometric font.")
        for path in (font, captions, model):
            shutil.copy2(path, self.delivery / "build" / path.name)

    def finish(self, lock, tools, flags):
        build = self.delivery / "build"
        shutil.copy2(__file__, build / Path(__file__).name)
        shutil.copy2(LOCK, build / LOCK.name)
        (build / "commands.json").write_text(json.dumps(self.commands, indent=2) + "\n", encoding="utf-8")
        versions = {}
        for command in ("gcc", "g++", "ld", "ar", "make", "nasm", "cmake", "ninja", "autoconf", "automake", "libtoolize", "pkg-config", "git", "gperf"):
            versions[command] = self.run([command, "--version"], capture=True, timeout=20)
        versions["meson"] = self.run([*self.meson, "--version"], capture=True, timeout=20)
        versions["xxd"] = self.run(["xxd", "-v"], capture=True, timeout=20)
        versions["os-release"] = Path("/etc/os-release").read_text(encoding="utf-8")
        versions["environment"] = {key: self.env[key] for key in ("CFLAGS", "CXXFLAGS", "CPPFLAGS", "LDFLAGS", "PKG_CONFIG_LIBDIR", "SOURCE_DATE_EPOCH")}
        (build / "toolchain.json").write_text(json.dumps(versions, indent=2) + "\n", encoding="utf-8")
        shutil.copy2(self.directory / "build.log", build / "build.log")
        provenance = {"schemaVersion": 1, "target": TARGET, "source": self.sources[0], "configure": flags, "tools": tools, "additionalSources": self.sources[1:], "licenses": self.licenses, "buildInputs": [record(path, self.delivery) for path in sorted(build.iterdir())]}
        (self.delivery / "build-provenance.json").write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8")
        print(f"Verified FFmpeg delivery: {self.delivery}", flush=True)


def validate_dependencies(text: str, prefix: Path):
    if "not found" in text or str(prefix) in text:
        raise ValueError("The FFmpeg pair has missing or temporary runtime dependencies.")
    observed = set()
    for line in text.splitlines():
        fields = line.split()
        first = fields[0] if fields else ""
        name = Path(first).name
        if first and not SYSTEM_LIBRARIES.fullmatch(name):
            raise ValueError(f"An unbundled codec/runtime library is required: {first}")
        observed.add(name)
    if not {"libc.so.6", "ld-linux-x86-64.so.2"}.issubset(observed):
        raise ValueError("The expected Linux C runtime and loader were not identified.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-directory", type=Path, required=True)
    parser.add_argument("--cache", type=Path, default=ROOT / "target/ffmpeg-package-source-cache")
    parser.add_argument("--jobs", type=int, default=min(os.cpu_count() or 2, 4))
    parser.add_argument("--verify-only", action="store_true")
    args = parser.parse_args()
    if sys.version_info < (3, 14):
        raise SystemExit("Python 3.14 or later is required for pinned Zstandard source bundles.")
    if not 1 <= args.jobs <= 32:
        raise SystemExit("Choose between 1 and 32 build workers.")
    if not args.verify_only and (sys.platform != "linux" or platform.machine().lower() not in {"x86_64", "amd64"}):
        raise SystemExit("This build targets Linux x86-64. Use --verify-only on another host.")
    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    if lock["schemaVersion"] != 1 or lock["target"] != TARGET:
        raise SystemExit("Unsupported Linux build lock.")
    builder = Builder(args.build_directory, args.cache, args.jobs)
    ffmpeg = builder.source(lock["ffmpeg"])
    if (ffmpeg / "RELEASE").read_text(encoding="utf-8").strip() != lock["ffmpeg"]["version"]:
        raise SystemExit("The extracted official FFmpeg release has a different identity.")
    sources = {item["id"]: builder.source(item) for item in lock["libraries"]}
    build_tools = {item["id"]: builder.source(item) for item in lock["buildTools"]}
    builder.meson = [sys.executable, str(build_tools["meson"] / "meson.py")]
    if args.verify_only:
        report = {"schemaVersion": 1, "compiled": False, "sources": builder.sources, "licenses": builder.licenses}
        (builder.directory / "source-verification.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
        print("All locked source archives and licenses verified; Linux compilation was not run.")
        return
    for identifier in ("bzip2", "zlib", "xz", "libogg", "libvorbis", "lame", "opus", "zimg", "x264", "libvpx", "dav1d", "x265", "expat", "brotli", "libpng", "freetype", "harfbuzz", "fribidi", "fontconfig", "libunibreak", "libass", "vmaf"):
        builder.library(identifier, sources[identifier])
    tools, flags = builder.ffmpeg(ffmpeg, lock["ffmpeg"]["version"])
    builder.finish(lock, tools, flags)


if __name__ == "__main__":
    main()
